---

# logging/playbooks/gather_diagnostics_play.yml
# Requires:  -e "log_time=<current time approximate> requests_file=<formatted request>" 

 - hosts: localhost
   gather_facts: yes
   tasks:

# Unfortunately, this variable is not available for the whole playbook
# only this play, and since it is time based, corner cases x:59:59 could 
# fail.  Instead require log_time to be passed in, whatever format is given works.

    # - name: set log_time
    #   set_fact:
    #     log_time: "{{ansible_date_time.date}}_{{ansible_date_time.time}}"
    # - debug: msg="{{log_time}}"

    - include_vars: "../files/{{request_file}}"

 - hosts: all
   roles:
    - ad_hoc_logging_and_diagnostics

 - hosts: localhost
   tasks:
     - include_vars: "../files/{{request_file}}"
     - include_vars: "../defaults/main.yml"

     - name: Mail the tarball to recipients
       mail: >
         body="tarball of logs for {{diagnostic_request.header.issue}}"
         from="{{diagnostic_request.header.email_from}}"
         to="{{diagnostic_request.header.email}}"
         attach="{{ad_hoc_logs_dir}}/{{diagnostic_request['header']['issue']}}_{{log_time}}.tar.gz"
         host="{{ad_hoc_mail_server}}"
         port=25
         subject="enjoy this tarball of logs for {{diagnostic_request.header.issue}}"